Replace FAIR.png with svg version. Fixes #23, #12.
NFDI4Energy/EFZN_rdm pull request #58
Opened 2023-09-08 10:38 UTC by rcschrg

Replaced FAIR.png with svg version.

2023-10-04 09:23 UTC, JuliaHeiken requested changes
The links are not clickable in the course. Please either remove them or embed the image in another way so that the links are working.

2023-10-10 09:37 UTC, rcschrg commented
Changed the embedding to object for interactive svg. Note that the svg link has to changed to the main branch after approval, otherwise there would be the need for another pull request, as this branch will eventually be deleted and the cached svg will be gone after seven days.

2023-10-11 09:21 UTC, JuliaHeiken requested changes
Links should open in a new tab and not inside the course

2023-10-11 09:34 UTC, JuliaHeiken approved these changes

2023-10-11 09:34 UTC, merged